feat - build sample data
ReportFxxkingMan/MessyArt pull request #1
Opened 2022-08-15 13:16 UTC by wonhyung64

## What does this PR do?
- build sample pos data

## How to test this? 
- 

## Does anything else need to be done?
-

2022-08-15 13:21 UTC, RektPunk requested changes
request changes :)

2022-08-15 13:21 UTC, RektPunk commented on data/mock_data.csv
> +____	__id	__	__	__	____
change colnames into english

2022-08-15 13:24 UTC, wonhyung64 commented on data/mock_data.csv
> +____	__id	__	__	__	____
ok :)

2022-08-16 02:09 UTC, RektPunk approved these changes
awesome

2022-08-16 02:25 UTC, merged