Feat/db link
ReportFxxkingMan/MessyArt pull request #5
Opened 2022-08-18 12:57 UTC by wonhyung64

## What does this PR do?
- modify connection_google_sheet and reconstruction

## How to test this? 
- 

## Does anything else need to be done?
-

2022-08-18 13:26 UTC, RektPunk requested changes
Sexy

2022-08-18 13:26 UTC, RektPunk commented on .env
> +GOOGLE_APPLICATION_CREDENTIALS = "./cred/token.json"
add eof

2022-08-18 13:26 UTC, RektPunk commented on module/database/variable.py
> +RANGE = 'db!A1:F'
요기두~

2022-08-18 13:26 UTC, RektPunk commented on module/database/variable.py
> +RANGE = 'db!A1:F'
이름 바꾸는게 좋을듯? range는 자주 쓰니까 헷갈릴지도

2022-08-18 13:26 UTC, RektPunk commented on module/database/google_sheet.py
> +def connect_google_sheet():
doc string 이 있으면 좋을듯

2022-08-18 13:26 UTC, RektPunk commented on run.py
> +def check_sheet(sheet, SPREADSHEET_ID, RANGE):
docstring, type hint

2022-08-18 13:26 UTC, RektPunk commented on module/database/google_sheet.py
> +    service = build('sheets', 'v4', credentials=creds)
질문) v4의 정체?

2022-08-18 13:26 UTC, RektPunk commented on run.py
> +#%%
```suggestion

```

2022-08-18 13:26 UTC, RektPunk commented on run.py
> +#%%
```suggestion
```

2022-08-18 13:30 UTC, RektPunk commented on .env
> +GOOGLE_APPLICATION_CREDENTIALS = "./cred/token.json"
```suggestion
GOOGLE_APPLICATION_CREDENTIALS = "./cred/token.json"

```

2022-08-18 13:31 UTC, RektPunk commented on module/database/variable.py
> +RANGE = 'db!A1:F'
```suggestion
RANGE = 'db!A1:F'

```

2022-08-18 14:08 UTC, wonhyung64 commented on module/database/variable.py
> +RANGE = 'db!A1:F'
옙 알겠슴다!

2022-08-18 14:09 UTC, wonhyung64 commented on .env
> +GOOGLE_APPLICATION_CREDENTIALS = "./cred/token.json"
yeaaaaaaap

2022-08-19 01:42 UTC, wonhyung64 reviewed
feedback accepted

2022-08-19 02:02 UTC, RektPunk approved these changes
Awesome!

2022-08-19 02:03 UTC, merged